apiVersion: v1
kind: PersistentVolume
metadata:
  name: vreiheit-postgres-pv
  labels:
    app: vreiheit
    ver: postgres-pv
spec:
  capacity:
    storage: "10Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/vreiheit/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - propero.dev
