apiVersion: v1
kind: PersistentVolume
metadata:
  name: vreiheit-postgres-pv
  labels:
    app: vreiheit
    ver: postgres-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
