kind: ConfigMap
apiVersion: v1
metadata:
  name: vreiheit-postgres-config
data:
  POSTGRES_DB: vreiheit
  POSTGRES_USER: vreiheit-postgres-user
  POSTGRES_PASSWORD: vreiheit-postgres-password
  PGDATA: /var/lib/postgresql/data
  