apiVersion: v1
kind: Service
metadata:
  name: vreiheit-website-service
  labels:
    app: vreiheit
    ver: service
spec:
  selector:
    app: vreiheit
    type: discord-bot-deployment
  ports:
    - port: 3000
