name: deploy-main
on:
  push:
    branches:
      - main
concurrency: production
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          docker build . -t ghcr.io/${{ secrets.GH_USERNAME }}/vreiheit-bot:${{ github.sha }} -t ghcr.io/${{ secrets.GH_USERNAME }}/vreiheit-bot:latest --build-arg=DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" --build-arg=DISCORD_CLIENT_ID="${{ secrets.DISCORD_CLIENT_ID }}" --build-arg=DISCORD_CLIENT_SECRET="${{ secrets.DISCORD_CLIENT_SECRET }}"
          docker push ghcr.io/${{ secrets.GH_USERNAME }}/vreiheit-bot:${{ github.sha }}
          docker push ghcr.io/${{ secrets.GH_USERNAME }}/vreiheit-bot:latest
      - uses: azure/setup-kubectl@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8_CONFIG }}
      - uses: azure/k8s-create-secret@v4
        with:
          container-registry-url: ghcr.io
          container-registry-username: ${{ secrets.GH_USERNAME }}
          container-registry-password: ${{ secrets.GH_TOKEN }}
          container-registry-email: ${{ secrets.GH_EMAIL }}
          secret-name: gh-registry-secret
          namespace: default
      - uses: azure/k8s-create-secret@v4
        with:
          namespace: default
          secret-type: generic
          secret-name: vreiheit-postgres
          string-data: ${{ secrets.POSTGRES_ENV }}
      - uses: azure/k8s-deploy@v4
        with:
          action: deploy
          strategy: basic
          manifests: manifests
          pull-images: false
          images: |
            ghcr.io/${{ secrets.GH_USERNAME }}/vreiheit-bot:${{ github.sha }}
          imagepullsecrets: |
            gh-registry-secret
