name: lint
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  checks: write
  contents: write


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm i -g pnpm && pnpm i --ignore-scripts
      - name: lint apps/server
        run: pnpm run packages:lint
